from __future__ import annotations

from typing import Protocol


class FileStore(Protocol):
    async def read(self, path: str) -> str: ...
    async def write(self, path: str, content: str) -> None: ...
    async def delete(self, path: str) -> None: ...
    async def list(self, path: str) -> list[str]: ...
    async def exists(self, path: str) -> bool: ...
    async def mkdir(self, path: str) -> None: ...
